package frc.controls;

public enum ButtonCode {
	A,
	B,
	X,
	Y,
	LEFTBUMPER,
	RIGHTBUMPER,
	BACK,
	START,
	LEFTSTICK,
	RIGHTSTICK,
	ELEVATOROVERRIDEDOWN,
	ELEVATOROVERRIDEUP,
	ARMOVERRIDEEXTEND,
	ARMOVERRIDERETRACT,
	CARGOSUCKOVERRIDE, 
	CARGOSPITOVERRIDE,
	BEAKRELEASEOVERRIDE,
	BEAKCAPTUREOVERRIDE,
	CARGOORHATCHPANEL,
	SETLOCATIONCARGOSHIP,
	SETLOCATIONROCKET,
	ROCKETHEIGHTHIGH,
	ROCKETHEIGHTMID,
	ROCKETHEIGHTLOW
}
